include $(CONFIG_FILE)

# === Source ===
app_source =
tst_source =


# === Build ===
test: $(app_source) $(tst_source)
	mkdir -p compiled
	mkdir -p compiled/objects

	@echo "Build Test Case"

.PHONY: test
